apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xfinity-data-usage.fullname" . }}-config
  labels:
    {{- include "xfinity-data-usage.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | nindent 4 }}
